%% Construct the data structure
Data=cell2struct(num2cell(data,1),[{'time'};ThisChName],2);

switch get(get(acqh,'SelectedObject'),'tag')
    case 'odor'
        newdata=cell2struct({Data,datatime,...
            menuname,menuscript,parameter,paratable,...
            odortable,thisOdor,thisValve,thisStim,thisFirstD,thisSecondD,thisTotalD},...
            {'data','time','menuname','scriptname',...
            'parameter','paratable','odortable','odor',...
            'valve','stim','FirstDilution','SecondDilution','TotalDilution'},2);
    otherwise
        newdata=cell2struct({Data,datatime,...
            menuname,menuscript,parameter,paratable},...
            {'data','time','menuname','scriptname',...
            'parameter','paratable'},2);
end


%% Save file
eval(['Data_' int2str(indexnum) '=newdata;'])
eval(['save ' savefile ' Data_' int2str(indexnum) ' -append'])
clear Data_*