%% Adapted from thacq.ver4

clearvars
close all
%daq.reset % Commented off b/c this will energizes all the valves!

OriginalCD=cd('C:\Users\higelab\Documents\GitHub\HigeLab\Chad\thstim\');

%% Customizable parameters

% Device ID of the nidaq board
NIdaq.ID='Dev2';

% Set up ai channels
% These channels will be recorded unless they're removed in each menu file
%   1st column: Channel label on the board
%   2nd column: Descriptive name of channel
%               Names will be used as the field names of data
%
% ao channels must be defined & added in each menu file
% 
% aichannels={'ai0','Pockels'...
%     ;'ai1','PID'...
%     ;'ai2','LED_command'...
%     ;'ai3','Shutter_command'...
%     };
% Set ao channel used for stimulus output
Sout={'ao0'};

% Set reference files
parameterfile='parameters.xls'; %First 10 worksheets will be loaded into menu
% presetodorfile='presetodors.mat'; %MAT file to recall preset odor choice
odorfile='odors.xls'; %List of odors with valve #


%% Setting up hardware objects

% Check nidaq board
HWlist=daq.getDevices;
for i=1:length(HWlist)
    if strcmpi(HWlist(i).Model,'USB-6001')
        NIdaq.dev=HWlist(i).ID;
        break
    end
end
if ~isfield(NIdaq,'dev')
    error('Nidaq board could not be found!')
end

% Make default session
% (May not use this session but may shorten the time to make next one)
% SS=MakeDefaultAISession(NIdaq.dev,aichannels);

% % Make analog output session to have immediate control of output
% aoSS=daq.createSession('ni');
% aoSS.addAnalogOutputChannel(NIdaq.dev,Sout,'voltage');
% outputSingleScan(aoSS,0);% Make sure ao is 0 by default

% olfactometer 

% AC=connectAlicat;%Connect to alicat controler
% Update COM port in connectAlicat.m if you change the port.
% shutAllValves_SS%Connect to USB6509
% Look up connectUSB6509_SS.m for the assignment of the dio channels
FillTime=2;%Time(sec) needed to odorize the tube.

%% Defining variables
menuscript='';

%% Setting up main fig objects
mainh=figure('Visible','off','numbertitle','off','Name','Stim_control','color',[1 .95 .95],...
    'Position',[800,40,1100,500],...
    'Toolbar','figure','DeleteFcn','closeacq');
fileh=uicontrol(mainh,'Style','text',...
    'Units','normalized',...
    'Position',[.01 .92 .38 .06],...
    'String','',...
    'FontUnits','normalized',...
    'Fontsize',0.8);
changefolderh=uicontrol(mainh,'Style','push',...
     'Units','normalized',...
    'Position',[.4 .92 .21 .06],...
    'String','Change Folder',...
    'FontUnits','normalized',...
    'Fontsize',0.6,...
    'callback','ChangeFolder');
statush=uicontrol(mainh,'Style','text','Units','normalized',...
    'Position',[.67 .7 .11 .26],'String','Idling',...
    'FontUnits','normalized',...
    'Fontsize',0.3,'back',[.5 1 .5]);
roundh=uicontrol(mainh,'Style','text','Units','normalized',...
    'Position',[.67 .65 .11 .2],...
    'String','',...
    'FontUnits','normalized',...
    'Fontsize',0.15,'back',get(mainh,'color'));
randomodorh=uicontrol(mainh,'style','radio','Units','normalized',...
    'position',[.67 .66 .11 .04],...
    'string','Randomize Odor',....
    'FontUnits','normalized',...
    'Fontsize',0.6,'back',get(mainh,'color'),...
    'value',0,'callback','');
runh=uicontrol(mainh,'Style','pushbutton','String','Run',...
    'Units','normalized',...
    'Position',[.79 .8 .09 .18],...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Callback','run');
stoph=uicontrol(mainh,'Style','pushbutton','String','Stop',...
    'Units','normalized',...
    'Position',[.89 .8 .09 .18],...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Callback','stopkey=1;');
pauseh=uicontrol(mainh,'Style','toggle','String','Pause',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.5,'Position',[.84 .68 .09 .1],'Callback','');
acqh=uibuttongroup('Parent',mainh,'Title','Acq menu',...
    'Position',[.01 .66 .6 .24],'back',[1 1 .7],...
    'SelectionChangeFcn','menuchange');

menu1h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.05 .535 .14 .395],...
    'visible','off','userdata',1);
menu2h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.24 .535 .14 .395],...
    'visible','off','userdata',2);
menu3h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.43 .535 .14 .395],...
    'visible','off','userdata',3);
menu4h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.62 .535 .14 .395],...
    'visible','off','userdata',4);
menu5h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.81 .535 .14 .395],...
    'visible','off','userdata',5);
menu6h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.05 .07 .14 .395],...
    'visible','off','userdata',6);
menu7h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.24 .07 .14 .395],...
    'visible','off','userdata',7);
menu8h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.43 .07 .14 .395],...
    'visible','off','userdata',8);
menu9h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.62 .07 .14 .395],...
    'visible','off','userdata',9);
menu10h=uicontrol(acqh,'Style','toggle','String','',...
    'Units','normalized',...
    'FontUnits','normalized',...
    'Fontsize',0.4,'Position',[.81 .07 .14 .395],...
    'visible','off','userdata',10);
parameterh=uipanel('Parent',mainh,'Title','Parameters',...
    'Position',[.45 .01 .54 .64],'visible','on');
edith=uicontrol('Parent',parameterh,'style','pushbutton','String','Edit',...
    'Units','normalized','Position',[.01 .02 .18 .1],...
    'FontUnits','normalized',...
    'Fontsize',0.6,'Callback',...
    'set(findobj(''tag'',''paratable''),''ColumnEditable'',logical([1 0]));set(tableRh,''visible'',''off'')');
odorpanelh=uipanel('Parent',mainh,'Title','Odors',...
    'Position',[.01 .01 .43 .56],'visible','on');
editodorh=uicontrol('Parent',odorpanelh,'style','pushbutton','String','Edit',...
    'Units','normalized','Position',[.01 .02 .18 .1],...
    'FontUnits','normalized','enable','off',...
    'Fontsize',0.6,'Callback','editodor');
addodorh=uicontrol('Parent',odorpanelh,'style','pushbutton','String','Add Odor',...
    'Units','normalized','Position',[.21 .02 .18 .1],...
    'FontUnits','normalized','enable','off',...
    'Fontsize',0.6,'Callback','addodor');
presetodorh=uicontrol('Parent',odorpanelh,'style','pushbutton','String','Preset',...
    'Units','normalized','Position',[.41 .02 .18 .1],...
    'FontUnits','normalized','enable','off',...
    'Fontsize',0.6,'Callback','loadpresetodor','visible','off');%Update call back, Inactive for now
nextodorh=uicontrol('Parent',odorpanelh,'style','text','String','',...
    'Units','normalized','Position',[.595 .02 .4 .1],...
    'FontUnits','normalized',...
    'Fontsize',0.5);

%% Loading menu file & odor table
warning('off')
[valve_dilution, odorlist]=xlsread(odorfile,1);
warning('on')
odorlist=odorlist(:,1)';
% odorlist=odorlist';
% sortedodorlist=[sort(odorlist),'DELETE THIS LINE!!'];
defOdorTableData=[num2cell(valve_dilution(:,1)),odorlist',num2cell(false(length(odorlist),1)),...
    num2cell(valve_dilution(:,3:4))];
for i=1:size(defOdorTableData,1)
    defOdorTableData{i,6}=CalcTotalDilution(defOdorTableData{i,4},defOdorTableData{i,5});
end

warning('off')
[typ,menulist]=xlsfinfo(parameterfile);
warning('on')

for i=1:min(length(menulist),10)
    warning('off')
    [num,txt]=xlsread(parameterfile,menulist{i});
    warning('on')
    eval(['paratable_' int2str(i) '=[txt(:,1:2) num2cell(num) txt(:,4)];']);
    eval(['para_' int2str(i) '=cell2struct(num2cell(num),txt(:,1),1);']);
    eval(['table' int2str(i) 'h=uitable(''parent'',parameterh,''units'',''normalized'','...
        '''position'',[.01 .15 .98 .84],'...
        '''rowname'', txt(:,2),''ColumnName'', {'''' ''unit''},'...
        '''data'', paratable_' int2str(i) '(:,3:4),'...
        '''FontUnits'',''Normalized'',''FontSize'',.065,'...
        '''ColumnEditable'',logical([0 0]),''tag'',''paratable'','...
        '''visible'',''on'',''CellEditCallback'',''paraedit'');']);
    eval(['set(menu' int2str(i) 'h,''string'',menulist{' int2str(i) '})']);
    eval(['set(menu' int2str(i) 'h,''visible'',''on'')']);
    eval(['menu' int2str(i) 'script=txt{1,5};']);
%     eval([txt{1,5} 'num=1;']); % menunum is not required
    if size(txt,2)>5
        if sum(strcmpi('odor',txt(:,6)))
            eval(['odortable' int2str(i) 'h=uitable(''parent'',odorpanelh,''units'',''normalized'','...
                '''position'',[.01 .15 .98 .84],'...
                '''ColumnWidth'',{35 110 35 50 50 60},'...
                '''ColumnName'', {''Valve'' ''Odor Name'' ''Stim'' ''1st d'' ''2nd d'' ''Total d''},'...
                '''data'',defOdorTableData,'...
                '''ColumnFormat'', {''numeric'',odorlist,''logical'',''numeric'',''numeric'',''numeric''},'...
                '''FontUnits'',''Normalized'',''FontSize'',.065,'...
                '''tag'',''odortable'','...
                '''visible'',''off'',''CellEditCallback'',''odorchange'','...
                '''CellSelectionCallback'',@odorselection);']);
            eval(['odortable_' int2str(i) '=get(odortable' int2str(i) 'h, ''data'');'])
            eval(['set(menu' int2str(i) 'h,''tag'',''odor'')']);
        end
    end
    
end

tableRh=uitable('parent',parameterh,'units','normalized',...
    'position',[.01 .15 .98 .84],'ColumnName', {'' 'unit'},...
    'FontUnits','Normalized','FontSize',.065,...
    'ColumnEditable',logical([0 0]),...
    'visible','off','tag','paratable','BackgroundColor',[1 1 .7]);

%% Make fig visible
set(acqh,'SelectedObject',[])   %Unselect acq menu
set(mainh,'Visible','on')       %Visualize figure
set(findobj('tag','paratable'),'visible','off')
%To bring tableRh to the top other tables must become
%visible at least once
pause(0.2) % wait for the main fig to be visible

%% Setting up file path
PathName=uigetdir('E:\Data\','Select Folder to Save Data');
if PathName==0
    close(mainh)
    return
end
